version: '2'

services: 
  # kafka cluster
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    environment: 
      ADV_HOST: 127.0.0.1
      RUNTEST: 0
    ports: 
      - 2181:2181                   # zookeeper  
      - 3030:3030                   # Landoop UI
      - 8081-8083:8081-8083         # Rest proxy , kafka connect ports
      - 9581-9585:9581-9585         # JMX porst
      - 9092:9092                   # Kafka broker
  
  elasticsearch:
    image: itzg/elasticsearch:2.4.3
    environment: 
      PLUGINS: appbaseio/dejavu
      OPTS: -Dindex.number_of_shards=1 -Dindex.number_of_replicas=0
    ports:
      - 9200:9200

  postgress:
    image: postgress:9.5-alpine
    environment: 
      POSTGRES_USER: postgress
      POSTGRESS_PASSWORD: postgress
      POSTGRESS_DB: postgress
    ports: 
      - 5432:5432

      
# docker run --rm -it -v "$(pwd)":/toturial --net=host
# landoop/fast-data-dev bash
# fast-data-dev / $ kafka-topics --create --topic demo-1-standalone --partirions 3 --replication-factor 1 --zookeeper 127.0.0.1:2181

